# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zhaxzhax 的博客
author: Zhaxzhax
description: > # this means to ignore newlines until "baseurl:"
  该主题基于 Mailbox Blog, 并采用 MIT 协议开源。
  该主题同时也是基于Jekyll Writer创建的网站的默认主题。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.zhaxzhax.cn" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: "/page/:num/"
twitter_username: hizhaxzhax
github_username:  zhaxzhax
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
